version: '3.8'

services:
  api:
    build: ./OSRS.proj.API
    container_name: osrsprojapi
    ports:
      - "5000:80"

  middleware:
    build: ./path-to-express
    container_name: osrs-express
    ports:
      - "3000:3000"
    depends_on:
      - api

  client:
    build: ./path-to-react
    container_name: osrs-react
    ports:
      - "8080:80"
    depends_on:
      - middleware
